package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/ramazanpolat/claude-playbooks/internal/auth"
	"github.com/ramazanpolat/claude-playbooks/internal/config"
	"github.com/ramazanpolat/claude-playbooks/internal/launcher"
	"github.com/ramazanpolat/claude-playbooks/internal/manifest"
)

var (
	createAlias   string
	createNoAlias bool
)

var createCmd = &cobra.Command{
	Use:   "create <name>",
	Short: "Create a new top-level playbook",
	Args:  cobra.ExactArgs(1),
	RunE:  runCreate,
}

func init() {
	createCmd.Flags().StringVar(&createAlias, "alias", "", "alias name (default: <name>)")
	createCmd.Flags().BoolVar(&createNoAlias, "no-alias", false, "skip alias creation")
}

func runCreate(cmd *cobra.Command, args []string) error {
	if createNoAlias && createAlias != "" {
		return fmt.Errorf("--no-alias and --alias cannot be used together")
	}

	name := args[0]
	if strings.Contains(name, "/") {
		return fmt.Errorf("playbook name cannot contain '/'")
	}
	if err := validateTopLevelName("playbook name", name); err != nil {
		return err
	}

	playbooksDir := config.ResolvePlaybooksDir()
	if err := os.MkdirAll(playbooksDir, 0755); err != nil {
		return err
	}
	dest := filepath.Join(playbooksDir, name)

	if _, err := os.Stat(dest); err == nil {
		return fmt.Errorf("playbook %q already exists at %s", name, dest)
	}

	// Preflight command names BEFORE the directory exists: once created it
	// joins the registry, and dispatch resolves directory names ahead of
	// aliases, so a clash would silently re-route an existing command.
	aliasName := createAlias
	if aliasName == "" {
		aliasName = name
	}
	if createAlias != "" {
		if err := launcher.ValidateName(createAlias); err != nil {
			return err
		}
	}
	// Serialize preflight-through-registration: without the registry lock,
	// two concurrent creates can both pass the ownership check and register
	// duplicate owners for one command name.
	unlock, err := lockRegistry()
	if err != nil {
		return err
	}
	defer unlock()

	// The directory name joins the registry even under --no-alias.
	preflightNames := []string{name}
	if !createNoAlias {
		preflightNames = append(preflightNames, aliasName)
	}
	if err := preflightCommandNames("", preflightNames...); err != nil {
		return err
	}

	if err := os.MkdirAll(dest, 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	if err := auth.SyncCredentials(dest); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: failed to sync credentials: %v\n", err)
	}

	if err := writeDefaultClaudeMD(dest, name); err != nil {
		return fmt.Errorf("failed to write CLAUDE.md: %w", err)
	}

	fmt.Printf("Created playbook %q at %s\n", name, dest)

	if createNoAlias {
		fmt.Printf("\nRun with:\n  claude-playbook run %s\n", name)
		return nil
	}

	// A custom command name must be resolvable at invocation time: record
	// it as the manifest alias so multicall dispatch finds the playbook.
	if aliasName != name {
		m := &manifest.Manifest{Version: "0.1.0", Name: name, Alias: aliasName}
		if err := manifest.Write(dest, m); err != nil {
			// Without the manifest entry the alias can never resolve.
			return fmt.Errorf("cannot record alias %q in manifest (required for the command to resolve): %w", aliasName, err)
		}
	}

	installLauncher(aliasName, name, dest)
	return nil
}

// defaultClaudeMD is written into a freshly created playbook so that the
// Claude Code session opened inside it knows what a playbook is and how this
// directory relates to the rest of the user's setup. Users are expected to
// edit or replace this file with playbook-specific instructions.
const defaultClaudeMD = "# Playbook: %s\n\n" +
	"This Claude Code session is running inside an **isolated playbook** — a self-contained Claude Code config directory managed by `claude-playbook`.\n\n" +
	"Your `CLAUDE_CONFIG_DIR` points to this directory, so settings, hooks, memory, conversation history, MCP servers, custom agents, slash commands, and this `CLAUDE.md` are all scoped here. Nothing in this playbook affects the user's default `~/.claude` install or other playbooks.\n\n" +
	"This directory is a playbook simply because it lives directly under the playbooks root — every direct child directory of that root is one playbook. You may optionally add a `.playbook` TOML manifest to set metadata (version, description, homepage, author), but it is not required for discovery.\n\n" +
	"## Useful `claude-playbook` commands\n\n" +
	"```\n" +
	"claude-playbook list           # list playbooks and aliases\n" +
	"claude-playbook info <name>    # show details for one\n" +
	"claude-playbook alias          # manage shell aliases\n" +
	"claude-playbook delete <name>  # remove a playbook\n" +
	"```\n\n" +
	"Full command reference: https://github.com/ramazanpolat/claude-playbooks\n\n" +
	"## Customizing\n\n" +
	"This `CLAUDE.md` was generated by `claude-playbook create`. Replace its contents with instructions for how *this* playbook should behave — that is what makes one playbook different from another.\n"

func writeDefaultClaudeMD(dir, name string) error {
	path := filepath.Join(dir, "CLAUDE.md")
	content := fmt.Sprintf(defaultClaudeMD, name)
	return os.WriteFile(path, []byte(content), 0644)
}
