package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/ramazanpolat/claude-playbooks/internal/auth"
	"github.com/ramazanpolat/claude-playbooks/internal/config"
	"github.com/ramazanpolat/claude-playbooks/internal/manifest"
	"github.com/ramazanpolat/claude-playbooks/internal/shell"
)

var (
	createAlias   string
	createNoAlias bool
)

var createCmd = &cobra.Command{
	Use:   "create <name>",
	Short: "Create a new top-level playbook",
	Args:  cobra.ExactArgs(1),
	RunE:  runCreate,
}

func init() {
	createCmd.Flags().StringVar(&createAlias, "alias", "", "alias name (default: <name>)")
	createCmd.Flags().BoolVar(&createNoAlias, "no-alias", false, "skip alias creation")
}

func runCreate(cmd *cobra.Command, args []string) error {
	if createNoAlias && createAlias != "" {
		return fmt.Errorf("--no-alias and --alias cannot be used together")
	}

	name := args[0]
	if strings.Contains(name, "/") {
		return fmt.Errorf("'create' only creates top-level playbooks. To add a child, declare it in the parent's .playbook")
	}
	if strings.HasPrefix(name, ".") {
		return fmt.Errorf("playbook name cannot start with '.'")
	}

	playbooksDir := config.ResolvePlaybooksDir()
	if err := os.MkdirAll(playbooksDir, 0755); err != nil {
		return err
	}
	dest := filepath.Join(playbooksDir, name)

	if _, err := os.Stat(dest); err == nil {
		return fmt.Errorf("playbook %q already exists at %s", name, dest)
	}

	if err := os.MkdirAll(dest, 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	if err := auth.SyncCredentials(dest); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: failed to sync credentials: %v\n", err)
	}

	if err := manifest.WriteMinimal(dest, name); err != nil {
		return fmt.Errorf("failed to write .playbook: %w", err)
	}

	if err := writeDefaultClaudeMD(dest, name); err != nil {
		return fmt.Errorf("failed to write CLAUDE.md: %w", err)
	}

	fmt.Printf("Created playbook %q at %s\n", name, dest)

	if createNoAlias {
		fmt.Printf("\nRun with:\n  claude-playbook run %s\n", name)
		return nil
	}

	aliasName := createAlias
	if aliasName == "" {
		aliasName = name
	}

	shellConfig, err := config.ResolveShellConfig()
	if err != nil {
		return err
	}

	if err := shell.Write(shellConfig, aliasName, dest); err != nil {
		return fmt.Errorf("failed to write alias: %w", err)
	}

	fmt.Printf("Alias %q added to %s\n", aliasName, shellConfig)
	fmt.Printf("\nReload your shell or run:\n  source %s\n\nThen run with:\n  %s\n", shellConfig, aliasName)
	return nil
}

// lastSegment returns the part after the last '/' in name.
func lastSegment(name string) string {
	i := strings.LastIndex(name, "/")
	if i < 0 {
		return name
	}
	return name[i+1:]
}

// defaultClaudeMD is written into a freshly created playbook so that the
// Claude Code session opened inside it knows what a playbook is and how this
// directory relates to the rest of the user's setup. Users are expected to
// edit or replace this file with playbook-specific instructions.
const defaultClaudeMD = "# Playbook: %s\n\n" +
	"This Claude Code session is running inside an **isolated playbook** — a self-contained Claude Code config directory managed by `claude-playbook`.\n\n" +
	"Your `CLAUDE_CONFIG_DIR` points to this directory, so settings, hooks, memory, conversation history, MCP servers, custom agents, slash commands, and this `CLAUDE.md` are all scoped here. Nothing in this playbook affects the user's default `~/.claude` install or other playbooks.\n\n" +
	"The directory is marked as a playbook by the `.playbook` TOML manifest in its root. Don't delete that file — it is the marker `claude-playbook` uses to discover this playbook.\n\n" +
	"## Useful `claude-playbook` commands\n\n" +
	"```\n" +
	"claude-playbook list           # list playbooks and aliases\n" +
	"claude-playbook info <name>    # show details for one\n" +
	"claude-playbook alias          # manage shell aliases\n" +
	"claude-playbook delete <name>  # remove a playbook\n" +
	"```\n\n" +
	"Full command reference: https://github.com/ramazanpolat/claude-playbooks\n\n" +
	"## Customizing\n\n" +
	"This `CLAUDE.md` was generated by `claude-playbook create`. Replace its contents with instructions for how *this* playbook should behave — that is what makes one playbook different from another.\n"

func writeDefaultClaudeMD(dir, name string) error {
	path := filepath.Join(dir, "CLAUDE.md")
	content := fmt.Sprintf(defaultClaudeMD, name)
	return os.WriteFile(path, []byte(content), 0644)
}
